#!/bin/bash

n=$(./ex4 "$1" | grep -n "^Scène $2\." | cut -d: -f1)
suivant=$(./ex4 "$1" | head -n $(($n+1)) | tail -1)

debut=$(grep -n "^Scène $2\." "$1" | cut -d: -f1)
fin=$(grep -n -x "$suivant" "$1" | cut -d: -f1)

cat "$1" | head -n $fin | tail -n +$debut | egrep "^[[:upper:]][[:upper:] ]*(:| \()" | egrep -o '^[^(:]+[^ (:]' | sort | uniq -c | sort -n -r
#cat "$1" | head -n $fin | tail -n +$debut | grep '^[[:upper:]][[:upper:] ]*:' | egrep -o '^[^(:]+[^ (:])' | sort | uniq -c | sort -n -r
